"""create audit logs

Revision ID: 1c394b4b451b
Revises: cb1145ad8c48
Create Date: 2026-09-02 14:31:58.091505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c394b4b451b'
down_revision: Union[str, Sequence[str], None] = 'cb1145ad8c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('career_personas', 'goal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_career_personas_user_id'), table_name='career_personas')
    op.drop_constraint(op.f('career_personas_user_id_fkey'), 'career_personas', type_='foreignkey')
    op.create_foreign_key(None, 'career_personas', 'users', ['user_id'], ['id'])
    op.drop_column('career_personas', 'updated_at')
    op.drop_column('career_personas', 'created_at')
    op.alter_column('jobs', 'openings',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'required_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'responsibilities',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'preferred_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'mandatory_requirements',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'preferred_requirements',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'screening_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'ats_configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_jobs_department'), 'jobs', ['department'], unique=False)
    op.alter_column('user_profiles', 'skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.drop_index(op.f('ix_jobs_department'), table_name='jobs')
    op.alter_column('jobs', 'ats_configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'{"skills": 30, "education": 15, "experience": 20, "certifications": 5, "role_relevance": 20, "screening_questions": 10}\'::jsonb'),
               existing_nullable=False)
    op.alter_column('jobs', 'screening_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('jobs', 'preferred_requirements',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('jobs', 'mandatory_requirements',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('jobs', 'preferred_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('jobs', 'responsibilities',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('jobs', 'required_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('jobs', 'openings',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.add_column('career_personas', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('career_personas', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'career_personas', type_='foreignkey')
    op.create_foreign_key(op.f('career_personas_user_id_fkey'), 'career_personas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_career_personas_user_id'), 'career_personas', ['user_id'], unique=True)
    op.alter_column('career_personas', 'goal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
