"""add career calendar

Revision ID: 1ee99a400a40
Revises: 10f04e4cf186
Create Date: 2026-08-21 23:24:13.754609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee99a400a40'
down_revision: Union[str, Sequence[str], None] = '10f04e4cf186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_persona_id', sa.UUID(), nullable=False),
    sa.Column('added_to_calendar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_persona_id'], ['career_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_calendars')
    # ### end Alembic commands ###
