"""add resume file to user profile

Revision ID: 31477cb46789
Revises: add_notifications
Create Date: 2026-09-07 16:51:34.446415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31477cb46789'
down_revision: Union[str, Sequence[str], None] = 'add_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_constraint(op.f('audit_logs_company_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.alter_column('jobs', 'job_code',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'JOB-' || nextval('public.job_code_seq')::text"),
               existing_nullable=False)
    op.drop_index(op.f('uq_jobs_job_code'), table_name='jobs')
    op.create_index(op.f('ix_jobs_job_code'), 'jobs', ['job_code'], unique=True)
    op.add_column('user_profiles', sa.Column('resume_file_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_profiles_resume_file_id'), 'user_profiles', ['resume_file_id'], unique=False)
    op.create_foreign_key(None, 'user_profiles', 'files', ['resume_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_user_profiles_resume_file_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'resume_file_id')
    op.drop_index(op.f('ix_jobs_job_code'), table_name='jobs')
    op.create_index(op.f('uq_jobs_job_code'), 'jobs', ['job_code'], unique=True)
    op.alter_column('jobs', 'job_code',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("('JOB-'::text || (nextval('job_code_seq'::regclass))::text)"),
               existing_nullable=False)
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_logs_company_id_fkey'), 'audit_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('notifications_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    # ### end Alembic commands ###
