"""add encrypted college admin password

Revision ID: 43b90d5249db
Revises: 919a26b3d308
Create Date: 2026-10-06 16:26:34.509420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b90d5249db'
down_revision: Union[str, Sequence[str], None] = '919a26b3d308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('admin_password_encrypted', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_password_encrypted')

    # ### end Alembic commands ###
