"""add master data table

Revision ID: 48f253fba588
Revises: ec35cac21c36
Create Date: 2026-08-19 15:12:21.623928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f253fba588'
down_revision: Union[str, Sequence[str], None] = 'ec35cac21c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_data',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_data_is_active'), 'master_data', ['is_active'], unique=False)
    op.create_index(op.f('ix_master_data_type'), 'master_data', ['type'], unique=False)
    op.create_index(op.f('ix_master_data_year'), 'master_data', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_data_year'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_type'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_is_active'), table_name='master_data')
    op.drop_table('master_data')
    # ### end Alembic commands ###
