"""remove xp from checkpoints

Revision ID: 919a26b3d308
Revises: 95a62d02c051
Create Date: 2026-10-01 14:01:18.653723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '919a26b3d308'
down_revision: Union[str, Sequence[str], None] = '95a62d02c051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkpoints', 'xp')
    op.alter_column('colleges', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('colleges', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jobs', 'job_code',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'JOB-' || nextval('public.job_code_seq')::text"),
               existing_nullable=False)
    op.alter_column('progress', 'mcqs_answered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('progress', 'mcqs_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress', 'mcqs_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('progress', 'mcqs_answered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('jobs', 'job_code',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("('JOB-'::text || (nextval('job_code_seq'::regclass))::text)"),
               existing_nullable=False)
    op.alter_column('colleges', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('colleges', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'India'::character varying"),
               existing_nullable=False)
    op.add_column('checkpoints', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
